//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Figaro.API.Models
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bdbxml.net/api/v1/containers.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Containers", Namespace = "http://schemas.bdbxml.net/api/v1/containers.xsd", IsNullable = false)]
    public partial class ContainerElementCollectionType
    {

        private ContainerElementType[] containerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Container", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContainerElementType[] Container
        {
            get
            {
                return this.containerField;
            }
            set
            {
                this.containerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bdbxml.net/api/v1/containers.xsd")]
    public partial class ContainerElementType
    {

        private string nameField;

        private string aliasField;

        private bool compressionField;

        private bool compressionFieldSpecified;

        private uint sequenceIncrementField;

        private bool sequenceIncrementFieldSpecified;

        private bool readUncommittedField;

        private bool encryptedField;

        private bool allowValidationField;

        private ConfigurationState statisticsField;

        private ConfigurationState indexNodesField;

        private bool transactionalField;

        private bool allowCreateField;

        private bool multiVersionField;

        private bool exclusiveCreateField;

        private bool noMMapField;

        private bool threadedField;

        private bool transactionNotDurableField;

        private XmlContainerType containerTypeField;

        public ContainerElementType()
        {
            this.readUncommittedField = false;
            this.encryptedField = false;
            this.allowValidationField = false;
            this.statisticsField = ConfigurationState.UseDefault;
            this.indexNodesField = ConfigurationState.UseDefault;
            this.transactionalField = false;
            this.allowCreateField = true;
            this.multiVersionField = false;
            this.exclusiveCreateField = false;
            this.noMMapField = false;
            this.threadedField = false;
            this.transactionNotDurableField = false;
            this.containerTypeField = XmlContainerType.WholeDocContainer;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool compression
        {
            get
            {
                return this.compressionField;
            }
            set
            {
                this.compressionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compressionSpecified
        {
            get
            {
                return this.compressionFieldSpecified;
            }
            set
            {
                this.compressionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint sequenceIncrement
        {
            get
            {
                return this.sequenceIncrementField;
            }
            set
            {
                this.sequenceIncrementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequenceIncrementSpecified
        {
            get
            {
                return this.sequenceIncrementFieldSpecified;
            }
            set
            {
                this.sequenceIncrementFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool readUncommitted
        {
            get
            {
                return this.readUncommittedField;
            }
            set
            {
                this.readUncommittedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool encrypted
        {
            get
            {
                return this.encryptedField;
            }
            set
            {
                this.encryptedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool allowValidation
        {
            get
            {
                return this.allowValidationField;
            }
            set
            {
                this.allowValidationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ConfigurationState.UseDefault)]
        public ConfigurationState statistics
        {
            get
            {
                return this.statisticsField;
            }
            set
            {
                this.statisticsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ConfigurationState.UseDefault)]
        public ConfigurationState indexNodes
        {
            get
            {
                return this.indexNodesField;
            }
            set
            {
                this.indexNodesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool transactional
        {
            get
            {
                return this.transactionalField;
            }
            set
            {
                this.transactionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool allowCreate
        {
            get
            {
                return this.allowCreateField;
            }
            set
            {
                this.allowCreateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool multiVersion
        {
            get
            {
                return this.multiVersionField;
            }
            set
            {
                this.multiVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool exclusiveCreate
        {
            get
            {
                return this.exclusiveCreateField;
            }
            set
            {
                this.exclusiveCreateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noMMap
        {
            get
            {
                return this.noMMapField;
            }
            set
            {
                this.noMMapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool threaded
        {
            get
            {
                return this.threadedField;
            }
            set
            {
                this.threadedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool transactionNotDurable
        {
            get
            {
                return this.transactionNotDurableField;
            }
            set
            {
                this.transactionNotDurableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(XmlContainerType.WholeDocContainer)]
        public XmlContainerType containerType
        {
            get
            {
                return this.containerTypeField;
            }
            set
            {
                this.containerTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bdbxml.net/api/v1/containers.xsd")]
    public enum ConfigurationState
    {

        /// <remarks/>
        On,

        /// <remarks/>
        Off,

        /// <remarks/>
        UseDefault,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bdbxml.net/api/v1/containers.xsd")]
    public enum XmlContainerType
    {

        /// <remarks/>
        NodeContainer,

        /// <remarks/>
        WholeDocContainer,
    }
}